#!/bin/bash

TMPDIR=`mktemp -d`
pushd $TMPDIR
wget -r www.breviar.sk/include
wget -r www.breviar.sk/include_cz
wget -r www.breviar.sk/include_hu
popd

cp -f $TMPDIR/www.breviar.sk/include/* include 
cp -f $TMPDIR/www.breviar.sk/include_cz/* include_cz
cp -f $TMPDIR/www.breviar.sk/include_hu/* include_hu

rm -rf $TMPDIR
